# Form implementation generated from reading ui file 'Ui_ComponentDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ComponentDialog(object):
    def setupUi(self, ComponentDialog):
        ComponentDialog.setObjectName("ComponentDialog")
        ComponentDialog.resize(660, 507)
        self.verticalLayout = QtWidgets.QVBoxLayout(ComponentDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layoutCheckboxes = QtWidgets.QHBoxLayout()
        self.layoutCheckboxes.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.layoutCheckboxes.setContentsMargins(-1, -1, -1, 0)
        self.layoutCheckboxes.setSpacing(6)
        self.layoutCheckboxes.setObjectName("layoutCheckboxes")
        self.verticalLayout_2.addLayout(self.layoutCheckboxes)
        self.layoutPlot = QtWidgets.QVBoxLayout()
        self.layoutPlot.setObjectName("layoutPlot")
        self.widget = QtWidgets.QWidget(parent=ComponentDialog)
        self.widget.setObjectName("widget")
        self.layoutPlot.addWidget(self.widget)
        self.verticalLayout_2.addLayout(self.layoutPlot)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ComponentDialog)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(ComponentDialog)
        self.buttonBox.accepted.connect(ComponentDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ComponentDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ComponentDialog)

    def retranslateUi(self, ComponentDialog):
        _translate = QtCore.QCoreApplication.translate
        ComponentDialog.setWindowTitle(_translate("ComponentDialog", "ICA - Komponenty"))
