# Form implementation generated from reading ui file 'Ui_HelpDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HelpDialog(object):
    def setupUi(self, HelpDialog):
        HelpDialog.setObjectName("HelpDialog")
        HelpDialog.resize(650, 420)
        self.verticalLayout = QtWidgets.QVBoxLayout(HelpDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblHelp = QtWidgets.QLabel(parent=HelpDialog)
        self.lblHelp.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.lblHelp.setScaledContents(False)
        self.lblHelp.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lblHelp.setWordWrap(True)
        self.lblHelp.setObjectName("lblHelp")
        self.verticalLayout.addWidget(self.lblHelp)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblAuthors = QtWidgets.QLabel(parent=HelpDialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblAuthors.setFont(font)
        self.lblAuthors.setObjectName("lblAuthors")
        self.horizontalLayout.addWidget(self.lblAuthors)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=HelpDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(HelpDialog)
        self.buttonBox.accepted.connect(HelpDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(HelpDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(HelpDialog)

    def retranslateUi(self, HelpDialog):
        _translate = QtCore.QCoreApplication.translate
        HelpDialog.setWindowTitle(_translate("HelpDialog", "ICA - Instrukcja"))
        self.lblHelp.setText(_translate("HelpDialog", "<html>\n"
"<head/>\n"
"<body>\n"
"<p>Kliknij przycisk <span style=\"font-weight:600;\">Importuj dane</span>:</p>\n"
"<ul>\n"
"  <li>Wczytaj plik CSV (każdy kanał w oddzielnej kolumnie).</li>\n"
"  <li>Opcjonalnie ustaw opcje pomijania wierszy, wyboru kolumn lub separatora.</li>\n"
"  <li>Dane zostaną wyświetlone w głównym oknie.</li>\n"
"</ul>\n"
"<p>Kliknij przycisk <span style=\"font-weight:600;\">Przeprowadź ICA</span>:</p>\n"
"<ul>\n"
"  <li>Wyświetlone zostaną odnalezione komponenty.</li>\n"
"  <li>Zaznacz checkboxy przy komponentach, które chcesz usunąć.</li>\n"
"</ul>\n"
"<p>Kliknij przycisk <span style=\"font-weight:600;\">Zaaplikuj ICA</span>:</p>\n"
"<ul>\n"
"  <li>Możesz zaaplikować ICA dla wybranych fragmentów (zaznacz je przeciągając myszką po oscylogramie, zaznaczanie można usuwać naciskająć na nie prawym przyciskiem myszy) lub całego sygnału (nie zaznaczając niczego).</li>\n"
"</ul>\n"
"<p>Kliknij przycisk <span style=\"font-weight:600;\">Eksportuj dane</span>:</p>\n"
"<ul>\n"
"  <li>Zapisz odseparowane sygnały do pliku CSV.</li>\n"
"</ul>\n"
"</body>\n"
"</html>"))
        self.lblAuthors.setText(_translate("HelpDialog", "Norbert Budzyński, Aleksandra Nawrocka"))
