# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bOpen = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bOpen.setObjectName("bOpen")
        self.horizontalLayout.addWidget(self.bOpen)
        self.bExport = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bExport.setEnabled(False)
        self.bExport.setObjectName("bExport")
        self.horizontalLayout.addWidget(self.bExport)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bICA = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bICA.setObjectName("bICA")
        self.horizontalLayout.addWidget(self.bICA)
        self.bApply = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bApply.setObjectName("bApply")
        self.horizontalLayout.addWidget(self.bApply)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.layoutPlot = QtWidgets.QVBoxLayout()
        self.layoutPlot.setObjectName("layoutPlot")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.layoutPlot.addWidget(self.widget)
        self.verticalLayout_2.addLayout(self.layoutPlot)
        self.verticalLayout_2.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ICA"))
        self.bOpen.setText(_translate("MainWindow", "Importuj dane"))
        self.bExport.setText(_translate("MainWindow", "Eksportuj dane"))
        self.bICA.setText(_translate("MainWindow", "Przeprowadź ICA"))
        self.bApply.setText(_translate("MainWindow", "Zaaplikuj ICA"))
